import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
import { syncCurrentUser } from "@/lib/sync-user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  await syncCurrentUser(); //comming from lib/ sync-user function we created forsyscning clerk user to db before laoding the layout for logged in user/created usr

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter} min-h-screen flex flex-col`}>
          {/* THEMEPROVIDER  */}
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {/* NAVBAR  */}
            <Navbar />
            {/* MAIN SECTION  */}
            <main className="flex-1 container ms-auto px-4 py-8">
              {children}
            </main>
            {/* FOOTER  */}
            <Footer />
            {/* TOASTER  */}
            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
